### ISSUE TITLE
ToDo list suggestions:

### ISSUE THREAD

**Issue by daaminashai** [Hackathon-CWL/DuckDistractions-HackathonCWL#2]
carry out these suggestions and once done check them out:-

- [x] add sound effects once the task is completed
- [x] make the logo geometrically fit the menubar (pic 1)
- [x] "To Do list" text should be middle aligned
- [x] add animation once task completed
- [x] change font of the task menu (pic 2)
- [x] remove strikethrough from delete button (pic 3)
- [x] sound effect for deletion of task
- [x] add wrap text to the tasks (pic 4)

Pic1
![image](https://github.com/user-attachments/assets/ca8e0593-b09e-4c3e-90a5-bff56161c16b)
Pic2
![image](https://github.com/user-attachments/assets/8989a70d-c3a4-4976-9ea8-2d8fa63b5bb2)
Pic3
![image](https://github.com/user-attachments/assets/a64f26bc-31d7-46f3-80aa-473ba87609d0)
Pic4
![image](https://github.com/user-attachments/assets/5886d021-bc01-4686-abaf-7f0ea20fa8e1)
